/*
 * This source file was generated by the Gradle 'init' task
 */
package sa.m;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    

    public static void main(String[] args) throws InterruptedException {
        Simulation simulation = new Simulation();
        simulation.runSimulation();    
    }
}
